---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - cedricziel
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "daily"
    assignees:
      - cedricziel
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - cedricziel
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
    assignees:
      - cedricziel
