version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=agentsaas
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
    image: golang:1.22
    working_dir: /app
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/agentsaas?sslmode=disable
      - PORT=8080
      - GOMODCACHE=/app/.gomodcache
      - GOCACHE=/app/.gocache
      - GOPROXY=https://proxy.golang.org,direct
      - OPENAI_API_KEY
    command: ["go", "run", "./cmd/server"]

volumes:
  db_data:
