/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AssistantChatRequest } from '../models';
// @ts-ignore
import type { AssistantChatResponse } from '../models';
/**
 * AssistantApi - axios parameter creator
 * @export
 */
export const AssistantApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Chat with AI assistant for workflow building
         * @param {string} agentId Agent ID
         * @param {AssistantChatRequest} assistantChatRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        assistantChat: async (agentId: string, assistantChatRequest: AssistantChatRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'agentId' is not null or undefined
            assertParamExists('assistantChat', 'agentId', agentId)
            // verify required parameter 'assistantChatRequest' is not null or undefined
            assertParamExists('assistantChat', 'assistantChatRequest', assistantChatRequest)
            const localVarPath = `/api/agents/{agentId}/assistant/chat`
                .replace(`{${"agentId"}}`, encodeURIComponent(String(agentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication ApiKeyAuth required
            await setApiKeyToObject(localVarHeaderParameter, "X-API-Key", configuration)

            // authentication BearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(assistantChatRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AssistantApi - functional programming interface
 * @export
 */
export const AssistantApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AssistantApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Chat with AI assistant for workflow building
         * @param {string} agentId Agent ID
         * @param {AssistantChatRequest} assistantChatRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async assistantChat(agentId: string, assistantChatRequest: AssistantChatRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AssistantChatResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.assistantChat(agentId, assistantChatRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AssistantApi.assistantChat']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AssistantApi - factory interface
 * @export
 */
export const AssistantApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AssistantApiFp(configuration)
    return {
        /**
         * 
         * @summary Chat with AI assistant for workflow building
         * @param {string} agentId Agent ID
         * @param {AssistantChatRequest} assistantChatRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        assistantChat(agentId: string, assistantChatRequest: AssistantChatRequest, options?: RawAxiosRequestConfig): AxiosPromise<AssistantChatResponse> {
            return localVarFp.assistantChat(agentId, assistantChatRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AssistantApi - object-oriented interface
 * @export
 * @class AssistantApi
 * @extends {BaseAPI}
 */
export class AssistantApi extends BaseAPI {
    /**
     * 
     * @summary Chat with AI assistant for workflow building
     * @param {string} agentId Agent ID
     * @param {AssistantChatRequest} assistantChatRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AssistantApi
     */
    public assistantChat(agentId: string, assistantChatRequest: AssistantChatRequest, options?: RawAxiosRequestConfig) {
        return AssistantApiFp(this.configuration).assistantChat(agentId, assistantChatRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

