package nodes

// Register all builder node definitions by blank-importing their packages.
import (
	_ "github.com/cedricziel/mel-agent/pkg/nodes/agent"
	_ "github.com/cedricziel/mel-agent/pkg/nodes/baserow"
	_ "github.com/cedricziel/mel-agent/pkg/nodes/db_query"
	_ "github.com/cedricziel/mel-agent/pkg/nodes/delay"
	_ "github.com/cedricziel/mel-agent/pkg/nodes/email"
	_ "github.com/cedricziel/mel-agent/pkg/nodes/file_io"
	_ "github.com/cedricziel/mel-agent/pkg/nodes/for_each"
	_ "github.com/cedricziel/mel-agent/pkg/nodes/http_request"
	_ "github.com/cedricziel/mel-agent/pkg/nodes/http_response"
	_ "github.com/cedricziel/mel-agent/pkg/nodes/if_node"
	_ "github.com/cedricziel/mel-agent/pkg/nodes/inject"
	_ "github.com/cedricziel/mel-agent/pkg/nodes/llm"
	_ "github.com/cedricziel/mel-agent/pkg/nodes/log"
	_ "github.com/cedricziel/mel-agent/pkg/nodes/manual_trigger"
	_ "github.com/cedricziel/mel-agent/pkg/nodes/merge"
	_ "github.com/cedricziel/mel-agent/pkg/nodes/noop"
	_ "github.com/cedricziel/mel-agent/pkg/nodes/random"
	_ "github.com/cedricziel/mel-agent/pkg/nodes/schedule"
	_ "github.com/cedricziel/mel-agent/pkg/nodes/script"
	_ "github.com/cedricziel/mel-agent/pkg/nodes/slack"
	_ "github.com/cedricziel/mel-agent/pkg/nodes/switch_node"
	_ "github.com/cedricziel/mel-agent/pkg/nodes/timer"
	_ "github.com/cedricziel/mel-agent/pkg/nodes/transform"
	_ "github.com/cedricziel/mel-agent/pkg/nodes/variable_get"
	_ "github.com/cedricziel/mel-agent/pkg/nodes/variable_list"
	_ "github.com/cedricziel/mel-agent/pkg/nodes/variable_set"
	_ "github.com/cedricziel/mel-agent/pkg/nodes/webhook"
	_ "github.com/cedricziel/mel-agent/pkg/nodes/workflow_call"
	_ "github.com/cedricziel/mel-agent/pkg/nodes/workflow_return"
	_ "github.com/cedricziel/mel-agent/pkg/nodes/workflow_trigger"
)
