/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AgentDeployment
 */
export interface AgentDeployment {
    /**
     * 
     * @type {string}
     * @memberof AgentDeployment
     */
    'agent_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof AgentDeployment
     */
    'version_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof AgentDeployment
     */
    'deployed_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof AgentDeployment
     */
    'status'?: AgentDeploymentStatusEnum;
}

export const AgentDeploymentStatusEnum = {
    Deploying: 'deploying',
    Deployed: 'deployed',
    Failed: 'failed'
} as const;

export type AgentDeploymentStatusEnum = typeof AgentDeploymentStatusEnum[keyof typeof AgentDeploymentStatusEnum];


