/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ChatChoice } from './chat-choice';
// May contain unused imports in some cases
// @ts-ignore
import type { ChatUsage } from './chat-usage';

/**
 * 
 * @export
 * @interface AssistantChatResponse
 */
export interface AssistantChatResponse {
    /**
     * Response ID
     * @type {string}
     * @memberof AssistantChatResponse
     */
    'id'?: string;
    /**
     * Object type (e.g., \"chat.completion\")
     * @type {string}
     * @memberof AssistantChatResponse
     */
    'object'?: string;
    /**
     * Unix timestamp
     * @type {number}
     * @memberof AssistantChatResponse
     */
    'created'?: number;
    /**
     * Model used
     * @type {string}
     * @memberof AssistantChatResponse
     */
    'model'?: string;
    /**
     * Array of response choices
     * @type {Array<ChatChoice>}
     * @memberof AssistantChatResponse
     */
    'choices'?: Array<ChatChoice>;
    /**
     * 
     * @type {ChatUsage}
     * @memberof AssistantChatResponse
     */
    'usage'?: ChatUsage;
}

