/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ChatChoice } from './chat-choice';
// May contain unused imports in some cases
// @ts-ignore
import type { ChatUsage } from './chat-usage';

export interface AssistantChatResponse {
    /**
     * Response ID
     */
    'id'?: string;
    /**
     * Object type (e.g., \"chat.completion\")
     */
    'object'?: string;
    /**
     * Unix timestamp
     */
    'created'?: number;
    /**
     * Model used
     */
    'model'?: string;
    /**
     * Array of response choices
     */
    'choices'?: Array<ChatChoice>;
    'usage'?: ChatUsage;
}

