/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Reason for finishing a chat completion
 * @export
 * @enum {string}
 */

export const ChatFinishReason = {
    Stop: 'stop',
    Length: 'length',
    FunctionCall: 'function_call'
} as const;

export type ChatFinishReason = typeof ChatFinishReason[keyof typeof ChatFinishReason];



