/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface ChatUsage {
    /**
     * Tokens used in prompt
     */
    'prompt_tokens'?: number;
    /**
     * Tokens used in completion
     */
    'completion_tokens'?: number;
    /**
     * Total tokens used
     */
    'total_tokens'?: number;
}

