/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ChatMessage } from './chat-message';

/**
 * 
 * @export
 * @interface ChatChoice
 */
export interface ChatChoice {
    /**
     * Choice index
     * @type {number}
     * @memberof ChatChoice
     */
    'index'?: number;
    /**
     * 
     * @type {ChatMessage}
     * @memberof ChatChoice
     */
    'message'?: ChatMessage;
    /**
     * Reason for finishing
     * @type {string}
     * @memberof ChatChoice
     */
    'finish_reason'?: ChatChoiceFinishReasonEnum;
}

export const ChatChoiceFinishReasonEnum = {
    Stop: 'stop',
    Length: 'length',
    FunctionCall: 'function_call'
} as const;

export type ChatChoiceFinishReasonEnum = typeof ChatChoiceFinishReasonEnum[keyof typeof ChatChoiceFinishReasonEnum];


