/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ChatMessageRole } from './chat-message-role';
// May contain unused imports in some cases
// @ts-ignore
import type { FunctionCall } from './function-call';

export interface ChatMessage {
    'role': ChatMessageRole;
    /**
     * Message content
     */
    'content': string;
    /**
     * Function name (for function role)
     */
    'name'?: string;
    'function_call'?: FunctionCall;
}



