/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CompleteWorkRequest {
    /**
     * The result of the completed work item
     */
    'result'?: { [key: string]: any; };
    /**
     * Error message if the work item failed
     */
    'error'?: string;
}

