/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { NodePosition } from './node-position';

export interface CreateWorkflowNodeRequest {
    'id': string;
    'name': string;
    'type': string;
    /**
     * Node configuration containing node-specific parameters and settings
     */
    'config': { [key: string]: any; };
    'position'?: NodePosition;
}

