/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateTriggerRequest
 */
export interface CreateTriggerRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateTriggerRequest
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof CreateTriggerRequest
     */
    'type': CreateTriggerRequestTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof CreateTriggerRequest
     */
    'workflow_id': string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateTriggerRequest
     */
    'config'?: { [key: string]: any; };
    /**
     * 
     * @type {boolean}
     * @memberof CreateTriggerRequest
     */
    'enabled'?: boolean;
}

export const CreateTriggerRequestTypeEnum = {
    Schedule: 'schedule',
    Webhook: 'webhook'
} as const;

export type CreateTriggerRequestTypeEnum = typeof CreateTriggerRequestTypeEnum[keyof typeof CreateTriggerRequestTypeEnum];


