/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CreateWorkflowNodeRequestPosition } from './create-workflow-node-request-position';

/**
 * 
 * @export
 * @interface CreateWorkflowNodeRequest
 */
export interface CreateWorkflowNodeRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateWorkflowNodeRequest
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof CreateWorkflowNodeRequest
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof CreateWorkflowNodeRequest
     */
    'type': string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CreateWorkflowNodeRequest
     */
    'config': { [key: string]: any; };
    /**
     * 
     * @type {CreateWorkflowNodeRequestPosition}
     * @memberof CreateWorkflowNodeRequest
     */
    'position'?: CreateWorkflowNodeRequestPosition;
}

