/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Credential
 */
export interface Credential {
    /**
     * 
     * @type {string}
     * @memberof Credential
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Credential
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Credential
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof Credential
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof Credential
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof Credential
     */
    'last_used'?: string;
    /**
     * 
     * @type {string}
     * @memberof Credential
     */
    'status'?: CredentialStatusEnum;
}

export const CredentialStatusEnum = {
    Valid: 'valid',
    Invalid: 'invalid',
    Expired: 'expired'
} as const;

export type CredentialStatusEnum = typeof CredentialStatusEnum[keyof typeof CredentialStatusEnum];


