/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CredentialType
 */
export interface CredentialType {
    /**
     * 
     * @type {string}
     * @memberof CredentialType
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof CredentialType
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CredentialType
     */
    'description'?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CredentialType
     */
    'schema'?: { [key: string]: any; };
    /**
     * 
     * @type {Array<string>}
     * @memberof CredentialType
     */
    'required_fields'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CredentialType
     */
    'test_endpoint'?: string;
}

