/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CredentialType {
    'id'?: string;
    'name'?: string;
    'description'?: string;
    'schema'?: { [key: string]: any; };
    'required_fields'?: Array<string>;
    'test_endpoint'?: string;
}

