/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CredentialTypeSchema
 */
export interface CredentialTypeSchema {
    /**
     * 
     * @type {string}
     * @memberof CredentialTypeSchema
     */
    'type'?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CredentialTypeSchema
     */
    'properties'?: { [key: string]: any; };
    /**
     * 
     * @type {Array<string>}
     * @memberof CredentialTypeSchema
     */
    'required'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof CredentialTypeSchema
     */
    'title'?: string;
    /**
     * 
     * @type {string}
     * @memberof CredentialTypeSchema
     */
    'description'?: string;
}

