/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ExecuteAgentNodeRequest
 */
export interface ExecuteAgentNodeRequest {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ExecuteAgentNodeRequest
     */
    'input'?: { [key: string]: any; };
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ExecuteAgentNodeRequest
     */
    'context'?: { [key: string]: any; };
}

