/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ParamSpec } from './param-spec';

export interface Extension {
    /**
     * Unique plugin identifier
     */
    'id': string;
    /**
     * Semver-compliant version string
     */
    'version': string;
    /**
     * Extension types provided (e.g. \"node\", \"trigger\")
     */
    'categories': Array<string>;
    /**
     * Parameter schema for configuration/UI
     */
    'params'?: Array<ParamSpec>;
    /**
     * Optional path or URL to React bundle
     */
    'ui_component'?: string;
}

