/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Integration
 */
export interface Integration {
    /**
     * 
     * @type {string}
     * @memberof Integration
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Integration
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Integration
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof Integration
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof Integration
     */
    'status'?: IntegrationStatusEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof Integration
     */
    'capabilities'?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Integration
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof Integration
     */
    'updated_at'?: string;
}

export const IntegrationStatusEnum = {
    Active: 'active',
    Inactive: 'inactive'
} as const;

export type IntegrationStatusEnum = typeof IntegrationStatusEnum[keyof typeof IntegrationStatusEnum];


