/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { IntegrationStatus } from './integration-status';

export interface Integration {
    'id'?: string;
    'name'?: string;
    'description'?: string;
    'type'?: string;
    'status'?: IntegrationStatus;
    'capabilities'?: Array<string>;
    /**
     * Type of credential required for this integration
     */
    'credential_type'?: string;
    'created_at'?: string;
    'updated_at'?: string;
}



