/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { IntegrationStatus } from './integration-status';

/**
 * 
 * @export
 * @interface Integration
 */
export interface Integration {
    /**
     * 
     * @type {string}
     * @memberof Integration
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Integration
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Integration
     */
    'description'?: string;
    /**
     * 
     * @type {string}
     * @memberof Integration
     */
    'type'?: string;
    /**
     * 
     * @type {IntegrationStatus}
     * @memberof Integration
     */
    'status'?: IntegrationStatus;
    /**
     * 
     * @type {Array<string>}
     * @memberof Integration
     */
    'capabilities'?: Array<string>;
    /**
     * Type of credential required for this integration
     * @type {string}
     * @memberof Integration
     */
    'credential_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof Integration
     */
    'created_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof Integration
     */
    'updated_at'?: string;
}



