/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { NodeInput } from './node-input';
// May contain unused imports in some cases
// @ts-ignore
import type { NodeKind } from './node-kind';
// May contain unused imports in some cases
// @ts-ignore
import type { NodeOutput } from './node-output';

export interface NodeType {
    'id'?: string;
    'name'?: string;
    'description'?: string;
    'kinds'?: Array<NodeKind>;
    'inputs'?: Array<NodeInput>;
    'outputs'?: Array<NodeOutput>;
}

