/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { NodeParameterOptionsOptionsInner } from './node-parameter-options-options-inner';

export interface NodeParameterOptions {
    'options'?: Array<NodeParameterOptionsOptionsInner>;
    'dynamic'?: boolean;
    'context_dependent'?: boolean;
}

