/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Kind of node functionality
 * @export
 * @enum {string}
 */

export const NodeKind = {
    Action: 'action',
    Model: 'model',
    Memory: 'memory',
    Tool: 'tool',
    Trigger: 'trigger'
} as const;

export type NodeKind = typeof NodeKind[keyof typeof NodeKind];



