/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NodeParameterOptionsOptionsInner
 */
export interface NodeParameterOptionsOptionsInner {
    /**
     * 
     * @type {string}
     * @memberof NodeParameterOptionsOptionsInner
     */
    'value'?: string;
    /**
     * 
     * @type {string}
     * @memberof NodeParameterOptionsOptionsInner
     */
    'label'?: string;
    /**
     * 
     * @type {string}
     * @memberof NodeParameterOptionsOptionsInner
     */
    'description'?: string;
}

