/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { NodeInput } from './node-input';
// May contain unused imports in some cases
// @ts-ignore
import type { NodeKind } from './node-kind';
// May contain unused imports in some cases
// @ts-ignore
import type { NodeOutput } from './node-output';

/**
 * 
 * @export
 * @interface NodeType
 */
export interface NodeType {
    /**
     * 
     * @type {string}
     * @memberof NodeType
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof NodeType
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof NodeType
     */
    'description'?: string;
    /**
     * 
     * @type {Array<NodeKind>}
     * @memberof NodeType
     */
    'kinds'?: Array<NodeKind>;
    /**
     * 
     * @type {Array<NodeInput>}
     * @memberof NodeType
     */
    'inputs'?: Array<NodeInput>;
    /**
     * 
     * @type {Array<NodeOutput>}
     * @memberof NodeType
     */
    'outputs'?: Array<NodeOutput>;
}

