/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Node position coordinates in the workflow canvas
 * @export
 * @interface NodePosition
 */
export interface NodePosition {
    /**
     * X coordinate position
     * @type {number}
     * @memberof NodePosition
     */
    'x'?: number;
    /**
     * Y coordinate position
     * @type {number}
     * @memberof NodePosition
     */
    'y'?: number;
}

