/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NodeInput
 */
export interface NodeInput {
    /**
     * 
     * @type {string}
     * @memberof NodeInput
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof NodeInput
     */
    'type'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof NodeInput
     */
    'required'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof NodeInput
     */
    'description'?: string;
}

