/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Type of trigger
 * @export
 * @enum {string}
 */

export const TriggerType = {
    Schedule: 'schedule',
    Webhook: 'webhook'
} as const;

export type TriggerType = typeof TriggerType[keyof typeof TriggerType];



