/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TriggerType } from './trigger-type';

export interface Trigger {
    'id'?: string;
    'name'?: string;
    'type'?: TriggerType;
    'workflow_id'?: string;
    /**
     * Trigger configuration containing trigger-specific parameters and settings
     */
    'config'?: { [key: string]: any; };
    'enabled'?: boolean;
    'created_at'?: string;
    'updated_at'?: string;
}



