/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateConnectionRequest
 */
export interface UpdateConnectionRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateConnectionRequest
     */
    'name'?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof UpdateConnectionRequest
     */
    'secret'?: { [key: string]: any; };
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof UpdateConnectionRequest
     */
    'config'?: { [key: string]: any; };
    /**
     * 
     * @type {number}
     * @memberof UpdateConnectionRequest
     */
    'usage_limit_month'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateConnectionRequest
     */
    'is_default'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof UpdateConnectionRequest
     */
    'status'?: UpdateConnectionRequestStatusEnum;
}

export const UpdateConnectionRequestStatusEnum = {
    Valid: 'valid',
    Invalid: 'invalid',
    Expired: 'expired'
} as const;

export type UpdateConnectionRequestStatusEnum = typeof UpdateConnectionRequestStatusEnum[keyof typeof UpdateConnectionRequestStatusEnum];


