/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ConnectionStatus } from './connection-status';

export interface UpdateConnectionRequest {
    'name'?: string;
    /**
     * Connection secret configuration containing authentication credentials
     */
    'secret'?: { [key: string]: any; };
    /**
     * Connection configuration containing non-sensitive connection parameters
     */
    'config'?: { [key: string]: any; };
    'usage_limit_month'?: number;
    'is_default'?: boolean;
    'status'?: ConnectionStatus;
}



