/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WorkflowStep
 */
export interface WorkflowStep {
    /**
     * 
     * @type {string}
     * @memberof WorkflowStep
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowStep
     */
    'run_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowStep
     */
    'node_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowStep
     */
    'status'?: WorkflowStepStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof WorkflowStep
     */
    'started_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowStep
     */
    'completed_at'?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof WorkflowStep
     */
    'input'?: { [key: string]: any; };
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof WorkflowStep
     */
    'output'?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof WorkflowStep
     */
    'error'?: string;
}

export const WorkflowStepStatusEnum = {
    Pending: 'pending',
    Running: 'running',
    Completed: 'completed',
    Failed: 'failed',
    Skipped: 'skipped'
} as const;

export type WorkflowStepStatusEnum = typeof WorkflowStepStatusEnum[keyof typeof WorkflowStepStatusEnum];


