/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WorkflowRun
 */
export interface WorkflowRun {
    /**
     * 
     * @type {string}
     * @memberof WorkflowRun
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowRun
     */
    'workflow_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowRun
     */
    'status'?: WorkflowRunStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof WorkflowRun
     */
    'started_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowRun
     */
    'completed_at'?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof WorkflowRun
     */
    'context'?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof WorkflowRun
     */
    'error'?: string;
}

export const WorkflowRunStatusEnum = {
    Pending: 'pending',
    Running: 'running',
    Completed: 'completed',
    Failed: 'failed'
} as const;

export type WorkflowRunStatusEnum = typeof WorkflowRunStatusEnum[keyof typeof WorkflowRunStatusEnum];


