/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WorkflowVersion } from './workflow-version';

/**
 * 
 * @export
 * @interface WorkflowVersionList
 */
export interface WorkflowVersionList {
    /**
     * 
     * @type {Array<WorkflowVersion>}
     * @memberof WorkflowVersionList
     */
    'versions': Array<WorkflowVersion>;
    /**
     * 
     * @type {number}
     * @memberof WorkflowVersionList
     */
    'total': number;
}

