/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WorkflowEdge
 */
export interface WorkflowEdge {
    /**
     * 
     * @type {string}
     * @memberof WorkflowEdge
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowEdge
     */
    'source': string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowEdge
     */
    'target': string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowEdge
     */
    'sourceOutput'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowEdge
     */
    'targetInput'?: string;
}

