/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Worker
 */
export interface Worker {
    /**
     * 
     * @type {string}
     * @memberof Worker
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Worker
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Worker
     */
    'status'?: WorkerStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof Worker
     */
    'last_heartbeat'?: string;
    /**
     * 
     * @type {number}
     * @memberof Worker
     */
    'concurrency'?: number;
    /**
     * 
     * @type {string}
     * @memberof Worker
     */
    'registered_at'?: string;
}

export const WorkerStatusEnum = {
    Active: 'active',
    Inactive: 'inactive'
} as const;

export type WorkerStatusEnum = typeof WorkerStatusEnum[keyof typeof WorkerStatusEnum];


