/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Workflow } from './workflow';

/**
 * 
 * @export
 * @interface WorkflowList
 */
export interface WorkflowList {
    /**
     * 
     * @type {Array<Workflow>}
     * @memberof WorkflowList
     */
    'workflows'?: Array<Workflow>;
    /**
     * 
     * @type {number}
     * @memberof WorkflowList
     */
    'total'?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkflowList
     */
    'page'?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkflowList
     */
    'limit'?: number;
}

