/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WorkflowStepStatus } from './workflow-step-status';

/**
 * 
 * @export
 * @interface WorkflowStep
 */
export interface WorkflowStep {
    /**
     * 
     * @type {string}
     * @memberof WorkflowStep
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowStep
     */
    'run_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowStep
     */
    'node_id'?: string;
    /**
     * 
     * @type {WorkflowStepStatus}
     * @memberof WorkflowStep
     */
    'status'?: WorkflowStepStatus;
    /**
     * 
     * @type {string}
     * @memberof WorkflowStep
     */
    'started_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowStep
     */
    'completed_at'?: string;
    /**
     * Generic input object containing arbitrary input data
     * @type {{ [key: string]: any; }}
     * @memberof WorkflowStep
     */
    'input'?: { [key: string]: any; };
    /**
     * Generic output object containing arbitrary output data
     * @type {{ [key: string]: any; }}
     * @memberof WorkflowStep
     */
    'output'?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof WorkflowStep
     */
    'error'?: string;
}



