/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WorkflowDefinition } from './workflow-definition';

/**
 * 
 * @export
 * @interface WorkflowVersion
 */
export interface WorkflowVersion {
    /**
     * 
     * @type {string}
     * @memberof WorkflowVersion
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowVersion
     */
    'workflow_id'?: string;
    /**
     * 
     * @type {number}
     * @memberof WorkflowVersion
     */
    'version_number'?: number;
    /**
     * 
     * @type {string}
     * @memberof WorkflowVersion
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowVersion
     */
    'description'?: string;
    /**
     * 
     * @type {WorkflowDefinition}
     * @memberof WorkflowVersion
     */
    'definition'?: WorkflowDefinition;
    /**
     * 
     * @type {boolean}
     * @memberof WorkflowVersion
     */
    'is_current'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof WorkflowVersion
     */
    'created_at'?: string;
}

