/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WorkflowDefinition } from './workflow-definition';

/**
 * 
 * @export
 * @interface WorkflowDraft
 */
export interface WorkflowDraft {
    /**
     * 
     * @type {string}
     * @memberof WorkflowDraft
     */
    'workflow_id'?: string;
    /**
     * 
     * @type {WorkflowDefinition}
     * @memberof WorkflowDraft
     */
    'definition'?: WorkflowDefinition;
    /**
     * 
     * @type {string}
     * @memberof WorkflowDraft
     */
    'updated_at'?: string;
}

