/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WorkflowEdge } from './workflow-edge';
// May contain unused imports in some cases
// @ts-ignore
import type { WorkflowNode } from './workflow-node';

/**
 * 
 * @export
 * @interface WorkflowDefinition
 */
export interface WorkflowDefinition {
    /**
     * 
     * @type {Array<WorkflowNode>}
     * @memberof WorkflowDefinition
     */
    'nodes': Array<WorkflowNode>;
    /**
     * 
     * @type {Array<WorkflowEdge>}
     * @memberof WorkflowDefinition
     */
    'edges': Array<WorkflowEdge>;
}

