/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WorkflowStepStatus } from './workflow-step-status';

export interface WorkflowStep {
    'id'?: string;
    'run_id'?: string;
    'node_id'?: string;
    'status'?: WorkflowStepStatus;
    'started_at'?: string;
    'completed_at'?: string;
    /**
     * Generic input object containing arbitrary input data
     */
    'input'?: { [key: string]: any; };
    /**
     * Generic output object containing arbitrary output data
     */
    'output'?: { [key: string]: any; };
    'error'?: string;
}



