/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WorkItem
 */
export interface WorkItem {
    /**
     * 
     * @type {string}
     * @memberof WorkItem
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkItem
     */
    'type'?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof WorkItem
     */
    'payload'?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof WorkItem
     */
    'created_at'?: string;
}

