/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WorkflowRun } from './workflow-run';

/**
 * 
 * @export
 * @interface WorkflowRunList
 */
export interface WorkflowRunList {
    /**
     * 
     * @type {Array<WorkflowRun>}
     * @memberof WorkflowRunList
     */
    'runs'?: Array<WorkflowRun>;
    /**
     * 
     * @type {number}
     * @memberof WorkflowRunList
     */
    'total'?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkflowRunList
     */
    'page'?: number;
    /**
     * 
     * @type {number}
     * @memberof WorkflowRunList
     */
    'limit'?: number;
}

