/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WorkflowNode
 */
export interface WorkflowNode {
    /**
     * 
     * @type {string}
     * @memberof WorkflowNode
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowNode
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowNode
     */
    'type': string;
    /**
     * Node configuration containing node-specific parameters and settings
     * @type {{ [key: string]: any; }}
     * @memberof WorkflowNode
     */
    'config': { [key: string]: any; };
}

