/* tslint:disable */
/* eslint-disable */
/**
 * MEL Agent API
 * AI Agents SaaS platform API with visual workflow builder
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { WorkflowRunStatus } from './workflow-run-status';

/**
 * 
 * @export
 * @interface WorkflowExecution
 */
export interface WorkflowExecution {
    /**
     * 
     * @type {string}
     * @memberof WorkflowExecution
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowExecution
     */
    'workflow_id'?: string;
    /**
     * 
     * @type {WorkflowRunStatus}
     * @memberof WorkflowExecution
     */
    'status'?: WorkflowRunStatus;
    /**
     * 
     * @type {string}
     * @memberof WorkflowExecution
     */
    'started_at'?: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowExecution
     */
    'completed_at'?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof WorkflowExecution
     */
    'result'?: { [key: string]: any; };
    /**
     * 
     * @type {string}
     * @memberof WorkflowExecution
     */
    'error'?: string;
}



