openapi: 3.0.3
info:
  title: MEL Agent API
  description: AI Agents SaaS platform API with visual workflow builder
  version: 1.0.0
  contact:
    name: MEL Agent Team
    url: https://github.com/cedricziel/mel-agent
  license:
    name: AGPL-3.0
    url: https://www.gnu.org/licenses/agpl-3.0.html
servers:
  - url: http://localhost:8080
    description: Local development server
  - url: https://api.mel-agent.com
    description: Production server
paths:
  /api/health:
    $ref: paths/api_health.yaml
  /api/workflows:
    $ref: paths/api_workflows.yaml
  /api/workflows/{id}:
    $ref: paths/api_workflows_{id}.yaml
  /api/workflows/{id}/execute:
    $ref: paths/api_workflows_{id}_execute.yaml
  /api/workflow-runs:
    $ref: paths/api_workflow-runs.yaml
  /api/workflow-runs/{id}:
    $ref: paths/api_workflow-runs_{id}.yaml
  /api/workflow-runs/{id}/steps:
    $ref: paths/api_workflow-runs_{id}_steps.yaml
  /api/node-types:
    $ref: paths/api_node-types.yaml
  /api/connections:
    $ref: paths/api_connections.yaml
  /api/connections/{id}:
    $ref: paths/api_connections_{id}.yaml
  /api/triggers:
    $ref: paths/api_triggers.yaml
  /api/triggers/{id}:
    $ref: paths/api_triggers_{id}.yaml
  /api/workers:
    $ref: paths/api_workers.yaml
  /api/workers/{id}:
    $ref: paths/api_workers_{id}.yaml
  /api/workers/{id}/heartbeat:
    $ref: paths/api_workers_{id}_heartbeat.yaml
  /api/workers/{id}/claim-work:
    $ref: paths/api_workers_{id}_claim-work.yaml
  /api/workers/{id}/complete-work/{itemId}:
    $ref: paths/api_workers_{id}_complete-work_{itemId}.yaml
  /api/workflows/{workflowId}/nodes:
    $ref: paths/api_workflows_{workflowId}_nodes.yaml
  /api/workflows/{workflowId}/nodes/{nodeId}:
    $ref: paths/api_workflows_{workflowId}_nodes_{nodeId}.yaml
  /api/workflows/{workflowId}/edges:
    $ref: paths/api_workflows_{workflowId}_edges.yaml
  /api/workflows/{workflowId}/edges/{edgeId}:
    $ref: paths/api_workflows_{workflowId}_edges_{edgeId}.yaml
  /api/workflows/{workflowId}/layout:
    $ref: paths/api_workflows_{workflowId}_layout.yaml
  /api/workflows/{workflowId}/draft:
    $ref: paths/api_workflows_{workflowId}_draft.yaml
  /api/workflows/{workflowId}/draft/nodes/{nodeId}/test:
    $ref: paths/api_workflows_{workflowId}_draft_nodes_{nodeId}_test.yaml
  /api/workflows/{workflowId}/versions:
    $ref: paths/api_workflows_{workflowId}_versions.yaml
  /api/workflows/{workflowId}/versions/latest:
    $ref: paths/api_workflows_{workflowId}_versions_latest.yaml
  /api/workflows/{workflowId}/versions/{versionNumber}/deploy:
    $ref: paths/api_workflows_{workflowId}_versions_{versionNumber}_deploy.yaml
  /api/credentials:
    $ref: paths/api_credentials.yaml
  /webhooks/{token}:
    $ref: paths/webhooks_{token}.yaml
  /api/integrations:
    $ref: paths/api_integrations.yaml
  /api/credential-types:
    $ref: paths/api_credential-types.yaml
  /api/credential-types/{type}/schema:
    $ref: paths/api_credential-types_{type}_schema.yaml
  /api/credential-types/{type}/test:
    $ref: paths/api_credential-types_{type}_test.yaml
  /api/node-types/{type}/parameters/{parameter}/options:
    $ref: paths/api_node-types_{type}_parameters_{parameter}_options.yaml
  /api/extensions:
    $ref: paths/api_extensions.yaml
  /api/assistant/chat:
    $ref: paths/api_assistant_chat.yaml
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
security:
  - BearerAuth: []
  - ApiKeyAuth: []
tags:
  - name: System
    description: System health and status endpoints
  - name: Workflows
    description: Workflow management endpoints
  - name: WorkflowRuns
    description: Workflow execution management
  - name: NodeTypes
    description: Node type discovery endpoints
  - name: Connections
    description: Integration connection management
  - name: Triggers
    description: Workflow trigger management
  - name: Workers
    description: Worker management endpoints
  - name: Webhooks
    description: External webhook handlers
  - name: Credentials
    description: Credential management for node connections
  - name: Integrations
    description: Available integration services
  - name: CredentialTypes
    description: Credential type definitions and schemas
