name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Backend tests and build
  backend:
    name: Backend Tests
    runs-on: ubuntu-24.04

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: agentsaas
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Go dependencies
        run: go mod download

      - name: Run Go tests
        run: go test ./...

      - name: Build server
        run: go build ./cmd/server

      - name: Upload server binary
        uses: actions/upload-artifact@v4
        with:
          name: server-binary
          path: server
          retention-days: 1

  # Frontend tests, lint, and build
  frontend:
    name: Frontend Tests & Build
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Cache Cypress binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            cypress-${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install

      - name: Install Cypress binary
        run: npx cypress install

      - name: Run frontend unit tests
        run: pnpm --filter agentsaas-web test:run

      - name: Lint frontend
        run: pnpm --filter agentsaas-web lint

      - name: Cache frontend build
        uses: actions/cache@v4
        with:
          path: web/dist
          key: frontend-build-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            frontend-build-${{ runner.os }}-

      - name: Build frontend
        run: pnpm --filter agentsaas-web build

      - name: Upload frontend build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: web/dist
          retention-days: 1

  # E2E tests with Cypress
  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-24.04
    needs: [backend, frontend]

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: agentsaas
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download server binary
        uses: actions/download-artifact@v5
        with:
          name: server-binary

      - name: Make server binary executable
        run: chmod +x server

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Cache Cypress binary
        uses: actions/cache@v4
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            cypress-${{ runner.os }}-

      - name: Cache frontend build
        id: cache-frontend
        uses: actions/cache@v4
        with:
          path: web/dist
          key: frontend-build-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            frontend-build-${{ runner.os }}-

      - name: Download frontend build (fallback)
        uses: actions/download-artifact@v5
        if: steps.cache-frontend.outputs.cache-hit != 'true'
        with:
          name: frontend-build
          path: web/dist

      - name: Install dependencies (needed for preview)
        run: pnpm install

      - name: Start backend server
        run: |
          ./server server &
          echo $! > server.pid
        env:
          PORT: 8080
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/agentsaas?sslmode=disable

      - name: Wait for backend to be ready
        run: |
          timeout 30 bash -c 'until curl -f http://localhost:8080/health; do sleep 1; done'

      - name: Start frontend preview server
        run: |
          pnpm --filter agentsaas-web preview --port 5173 &
          echo $! > preview.pid

      - name: Wait for frontend to be ready
        run: |
          timeout 30 bash -c 'until curl -f http://localhost:5173; do sleep 1; done'

      - name: Run Cypress E2E tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: web
          install: false
          browser: chrome
          spec: cypress/e2e/**/*.cy.js
        env:
          CYPRESS_baseUrl: http://localhost:5173
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: web/cypress/screenshots
          retention-days: 7

      - name: Upload Cypress videos
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: web/cypress/videos
          retention-days: 7

      - name: Stop servers
        if: always()
        run: |
          if [ -f server.pid ]; then
            kill $(cat server.pid) || true
            rm server.pid
          fi
          if [ -f web/preview.pid ]; then
            kill $(cat web/preview.pid) || true
            rm web/preview.pid
          fi
